### ISSUE TITLE
[Bug] 로그아웃 에러

### ISSUE THREAD

**Issue by geon5595** [Kim-Dong-Hyeon/KickBoardApp#53]
## 어떤 버그인가요?

> 로그아웃 시 크래시 발생

## 어떤 상황에서 발생한 버그인가요?

> 로그아웃 시 크래시 발생

## 예상 결과

>

**Comment by Kim-Dong-Hyeon** [comment]
mapController resetEngine 을 안해줘서 생겼던 문제였습니다.

resetEngine 을 해주면 TabBar 넘어갈때 초기화 되는 문제가 있어 주석처리 하였었는데 고게 문제였나봅니다.(ViewWillDisappear에 있었음)
deinit에 추가해서 해결되었습니다.
